### ISSUE TITLE
Support for stratum server login

### ISSUE THREAD

**Issue by jaspervdm** [mozkomor/GrinGoldMiner#8] opened 2018-06-28 02:13 UTC
The default grin miner supports a stratum login (see [grin-miner.toml](https://github.com/mimblewimble/grin-miner/blob/master/grin-miner.toml#L46)) and password. It would be great if this could be implemented into GrinGoldMiner as well, especially now since the first pool implementation is in the testing phase.

**Comment by phooton** [comment] 2018-06-28 14:58
I've added -l and -p parameters. It sends the rpc command, but grin node does not react to it. So not sure if it works. I assume a proper pool will confirm the login request. It would be visible as a green text in console window.

**Comment by phooton** [comment] 2018-06-28 15:18
Made is compatible with grinpool.us:3333, but it kicks me out after the first submitted share so don't expect it to work atm.

**Comment by bladedoyle** [comment] 2018-06-28 18:12
The built-in stratum server in the grin node responds to a valid login request with an "ok" response.  ex:

Login Request sent by the miner:
{"id":"Stratum","jsonrpc":"2.0","method":"login","params":{"agent":"telnet","login":"myLogin","pass":""}}

Expected success reply from the Stratum server:
{"id":"Stratum","jsonrpc":"2.0","method":"login","result":"ok","error":null}

Note:  For login requests all 3 parameters must be sent

**Comment by bladedoyle** [comment] 2018-06-28 23:28
Although I can see the miner disconnect in the grinpool.us logs, I cant tell exactly what caused it.  I did fix the missing login "ok" response, and I added some additional error checking and logging in the problem area.  I hope to be able to see the cause next time it happens.

**Comment by phooton** [comment] 2018-06-28 23:37
I see the login ok message now. I don't seem to get any responses to share submits. Perhaps I'm required to use the ID in all messages?

**Comment by bladedoyle** [comment] 2018-06-29 19:54
I was able to identify the issue - it is related to the pools indexing into the worker array.  I will work on a better fix over the weekend.

**Comment by phooton** [comment] 2018-07-29 13:55
Presumably fixed now.

**Closed by phooton** 2018-07-29 13:55 UTC
